name: Deploy static content to Pages

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Allow the actions bot to push to the repo
          token: ${{ secrets.GITHUB_TOKEN }}

      # Debug information
      - name: Debug
        run: |
          echo "Debugging..."
          cd frontend
          pwd
          ls
          echo "Environment variables:"
          printenv
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v

      # Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # Install dependencies (use the frontend directory explicitly)
      - name: Install dependencies
        run: |
          npm ci
        working-directory: ./frontend

      # Build the Vite project
      - name: Build
        run: npm run build
        working-directory: ./frontend

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
